name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pythonanywhere

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        pa_autoconfigure_django.py --nuke --python=3.9 https://github.com/shivaniindoria/tws-pro.git

    - name: Reload the web app
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/webapps/$USERNAME.pythonanywhere.com/reload/" \
             -H "Authorization: Token $API_TOKEN"
